imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 14  # Ensure the version matches your project's requirements
            commands:
                - command: "composer install"
                - command: "npm install"  # or "yarn install" if you use yarn
                - command: "npm run build"  # or "yarn build" if you use yarn
                - command: "composer phpunit"  # Ensure this matches your local test script

        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file

    tests:
        override:
            -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
