<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYCkGMXg\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYCkGMXg/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYCkGMXg.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYCkGMXg\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerYCkGMXg\App_KernelTestDebugContainer([
    'container.build_hash' => 'YCkGMXg',
    'container.build_id' => '6948c7b9',
    'container.build_time' => 1724334673,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYCkGMXg');
