<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJKdWX1F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJKdWX1F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJKdWX1F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJKdWX1F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJKdWX1F\App_KernelDevDebugContainer([
    'container.build_hash' => 'JKdWX1F',
    'container.build_id' => '7512d3f7',
    'container.build_time' => 1716036190,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJKdWX1F');
