<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMFj1kGI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMFj1kGI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMFj1kGI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMFj1kGI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMFj1kGI\App_KernelDevDebugContainer([
    'container.build_hash' => 'MFj1kGI',
    'container.build_id' => '322cd37c',
    'container.build_time' => 1724338695,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMFj1kGI');
